机器重启后， 不仅看重启的命令， 也要看


sudo mount -t nfs -o vers=3,nolock,proto=tcp,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 24f3f480ea-qmd96.cn-shenzhen.nas.aliyuncs.com:/ /var/tmp/filecoin-proof-parameters/


nohup ./floader ./lotus daemon --server-api=http://10.10.28.218:3456 --bootstrap=false --api 11234 > lotus.log 2>&1 &


FORCE_BUILDER_P1_WORKERS=18 FORCE_BUILDER_TASK_DELAY=1s FORCE_BUILDER_AUTO_PLEDGE_INTERVAL=1 TRUST_PARAMS=1 RUST_LOG=info RUST_BACKTRACE=1 FORCE_BUILDER_PLEDGE_TASK_TOTAL_NUM=37 nohup ./floader ./lotus-storage-miner run --mode=remote-sealer --server-api=http://10.10.28.218:3456 --dist-path=/var/tmp/filecoin-proof-parameters --nosync --groups=1 > ./sealer.log 2>&1 &


TRUST_PARAMS=1 RUST_LOG=info RUST_BACKTRACE=1 nohup ./floader ./lotus-storage-miner run --mode=remote-wdposter --server-api=http://10.10.28.218:3456 --dist-path=/var/tmp/filecoin-proof-parameters --nosync > poster.log 2>&1 &



### worker

amd:
FIL_PROOFS_HUGEPAGE_MOUNT=/mnt/huge/ FORCE_OPT_P1=1 FIL_PROOFS_NUMS_OF_PARTITION_FORCE=2 FIL_PROOFS_MAXIMIZE_CACHING=true FIL_PROOFS_ALLOW_GENERATING_GROTH=1 RUST_LOG=trace FORCE_HUGE_PAGE=1  RUST_BACKTRACE=1 nohup  ./floader ./force-remote-worker-tmp  > force-remote-worker-tmp.log 2>&1  &

intel:
FORCE_OPT_P1=1 FIL_PROOFS_NUMS_OF_PARTITION_FORCE=4 FIL_PROOFS_MAXIMIZE_CACHING=false FIL_PROOFS_ALLOW_GENERATING_GROTH=1 RUST_LOG=debug BELLMAN_PROOF_THREADS=3 RUST_BACKTRACE=1 nohup ./floader ./force-remote-worker > force-remote-worker.log 2>&1 &




#### docker 重名， 导致起不来
 [root@amd docker]# docker-compose up -d
Creating p1 ... error
Creating p4-2 ...
Creating p4-3 ...
Creating p4-3 ... done

ERROR: for p1  Cannot create container for service bench1: b'Conflict. The container name "/p1" is already in use by container 0020d63f25a0a36a5e9b1f15ce452b634447938236c9907628d745e76f7ee64d. You have to remove (or rename) that container to be able to reuse that name.'

ERROR: for bench1  Cannot create container for service bench1: b'Conflict. The container name "/p1" is already in use by container 0020d63f25a0a36a5e9b1f15ce452b634447938236c9907628d745e76f7ee64d. You have to remove (or rename) that container to be able to reuse that name.'
ERROR: Encountered errors while bringing up the project.
[root@amd docker]# vi docker-compose.yml
[root@amd docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                    PORTS               NAMES
bfdf4bca1b3d        test                "tail -f /dev/null"      About a minute ago   Up About a minute                             p4-3
db1914ce327d        test                "tail -f /dev/null"      About a minute ago   Up About a minute                             p4-2
0fc6658b3c5c        test                "tail -f /dev/null"      About a minute ago   Up About a minute                             p4-1
f805e40caa19        cpu                 "tail -f /dev/null"      3 days ago           Exited (137) 3 days ago                       p2
0020d63f25a0        cpu                 "/bin/bash"              3 days ago           Exited (0) 3 days ago                         p1
c70450fa2d6e        040f01151764        "/bin/sh -c 'yum i..."   6 days ago           Exited (0) 6 days ago                         lucid_kare


